<?php
/**
 * @author     X2Y Development team <dev@x2y.io>
 * @copyright  2023 X2Y Development team
 */
/**
 * @var $escaper Magento\Framework\Escaper
 * @var $block Ecentric\Payment\Block\Checkout\Ecentric
 */

$formData = $block->getFormData();
?>

<?php if (!empty($formData)) : ?>
    <form method="post" id="ecentric_payment" action="<?= $escaper->escapeUrl($block->getRedirectUrl()); ?>">
        <?php foreach ($formData as $name => $value): ?>
            <input type="hidden" name="<?= $name ?>" value="<?= $value ?>">
        <?php endforeach; ?>
    </form>
    <script>
        document.getElementById('ecentric_payment').submit();
    </script>
<?php endif; ?>
