<?php
$params = $this->getParameters();
if(!empty($params)){
	if($params['fail_message']){ ?>
		<p>Payment has failed because <b><?php echo $params['fail_message']; ?></b></p>
	<?php } ?>
	<div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php echo $this->getBaseUrl(); ?>"><span>Continue Shopping</span></a>
        </div>
    </div>
<?php } ?>