<?php
use Ecentric\Payment\Block\Customer\WalletManagement;
use Magento\Framework\Escaper;

/**
 * @author     X2Y Development team <dev@x2y.io>
 * @copyright  2023 X2Y Development team
 */
/** @var $escaper Escaper */
/** @var $block WalletManagement */

$formParameters = $block->getWalletParameters();
?>
<?php if ($formParameters) : ?>
    <button id="ecentric_submit" class="action primary"><?= __('Manage Your Wallet') ?></button>
    <script type="text/x-magento-init">
        {
            "*": {
                "ecentricCustomerWallet": {
                    "mode": "<?= $escaper->escapeJs($block->getApiMode()) ?>",
                    "merchantId": "<?= $escaper->escapeJs($formParameters['MerchantID']) ?>",
                    "userId": "<?= $escaper->escapeJs($formParameters['UserID']) ?>",
                    "checksum": "<?= $escaper->escapeJs($formParameters['Checksum']) ?>"
                }
            }
        }
    </script>
<?php endif; ?>


