<?php
use Ecentric\Payment\Block\Customer\WalletManagement;
use Magento\Framework\Escaper;

/**
 * @author     X2Y Development team <dev@x2y.io>
 * @copyright  2023 X2Y Development team
 */
/** @var $escaper Escaper */
/** @var $block WalletManagement */

$formParameters = $block->getWalletParameters();
?>
<?php if ($formParameters) : ?>
    <?php foreach ($formParameters as $name => $value): ?>
        <input type="hidden" name="<?= $name; ?>" value="<?= $value; ?>">
    <?php endforeach; ?>
    <button id="ecentric_submit" class="action primary"><?= __('Manage Your Wallet') ?></button>

    <script>
        require([
            'jquery',
            'ecentricJs'
        ], function ($, ecentricJs) {
            $('#ecentric_submit').on('click', function () {
                    var cardModel = {
                        MerchantID: $("input[name=MerchantID]").val(),
                        UserID: $("input[name=UserID]").val(),
                        Checksum: $("input[name=Checksum]").val()
                    }
                    ecentricJs.addCard(cardModel)
                }
            )
        });
    </script>
<?php endif; ?>


